const val JACKSON_VERSION = "+"
const val REACTOR_NETTY_VERSION = "+"
const val JUNIT_VERSION = "+"
const val JGIT_VERSION = "+"
const val LOGBACK_VERSION = "+"
const val SPRING_WEB_VERSION = "+"
const val JSR_305_VERSION = "+"
const val COMMONMARK_VERSION = "+"
