const val JACKSON_VERSION = "[2.10,)"
const val REACTOR_NETTY_VERSION = "[0.9,)"
const val JUNIT_VERSION = "[5.6,)"
const val JGIT_VERSION = "[5.7,)"
const val LOGBACK_VERSION = "[1.2,)"
const val SPRING_WEB_VERSION = "5.+"
const val JSR_305_VERSION = "3.0.2"
const val COMMONMARK_VERSION = "[0.15.2,)"
