openapi: "3.0.0"
info:
  version: 1.0.0
  title: TODO
servers:
  - url: http://localhost/
paths:
  /:
    post:
      operationId: create
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'item.yaml'
      responses:
        '200':
          description: description
          content:
            application/json:
              schema:
                type: string
  /post-without-request-body:
    post:
      operationId: post-without-request-body
      responses:
        '200':
          description: description
          content:
            application/json:
              schema:
                type: string
  /find:
    get:
      operationId: find
      parameters:
        - name: param1
          in: query
          required: true
          schema:
            type: string
        - name: param2
          in: query
          required: false
          schema:
            type: string
        - name: param3
          in: query
          required: false
          schema:
            $ref: 'enum-item.yaml'
          example: 'VALUE_1'
      responses:
        '200':
          description: description
          content:
            application/json:
              schema:
                $ref: 'item.yaml'
  /{id}:
    get:
      operationId: get
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: description
          content:
            application/json:
              schema:
                $ref: 'item.yaml'
