openapi: "3.0.0"
info:
  version: 1.0.0
  title: Simple schema
servers:
  - url: http://localhost/
paths:
  /path1:
    post:
      operationId: simple post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dto'
      responses:
        '200':
          description: description
          content:
            application/json:
              schema:
                type: string
  /path2/{id}:
    get:
      operationId: simple get
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: param1
          in: query
          required: true
          schema:
            type: string
        - name: param2
          in: query
          required: false
          schema:
            title: Dto title
            description: Dto description
            type: string
            enum:
              - value1
              - value2
        - in: header
          name: param3-header
          schema:
            type: string
            format: date
      responses:
        '200':
          description: description
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dto'
  /path3:
    post:
      operationId: test nullable parameter
      parameters:
        - name: param1
          in: query
          schema:
            type: string
            format: date
          required: false
      responses:
        '200':
          description: description
  /path4:
    get:
      operationId: return octet stream
      responses:
        200:
          description: description
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
  /path5:
    post:
      operationId: send octet stream
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        200:
          description: description
components:
  schemas:
    dto:
      type: object
      properties:
        property1:
          type: string
