openapi: "3.0.0"
info:
  version: 1.0.0
  title: Simple schema
servers:
  - url: http://localhost/
paths:
  /path1:
    post:
      operationId: simple post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dto'
      responses:
        '200':
          description: description
          content:
            application/json:
              schema:
                type: string
  /path2/{id}:
    get:
      operationId: simple get
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: param1
          in: query
          required: true
          schema:
            type: string
        - name: param2
          in: query
          required: false
          schema:
            title: Dto title
            description: Dto description
            type: string
            enum:
              - value1
              - value2
      responses:
        '200':
          description: description
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dto'

components:
  schemas:
    dto:
      type: object
      properties:
        property1:
          type: string
